### ISSUE TITLE
Wrong Path Setting  in boothgalery/modules/uniqueID/index.php

### ISSUE THREAD

**Issue by shortyxs** [tippexs/boothgalery#1]
In [https://github.com/tippexs/boothgalery/blob/master/modules/uniqueID/index.php](url) on line 25, there is an absolut path linking to the conf.php. This should be a relative path like 
`<?php require_once '/../../etc/conf.php'; ?>`
Otherwise it is kind of useless to have a central config file, if I need to match other files anyway.

**Comment by tippexs** [comment]
Hy shortsyxs - Thanks for your work on that!

Currently, i am updating the uniqueID module. Update will be available today.

**Comment by tippexs** [comment]
Done! Thanks for opening an issue.
